
 Recording {
    setProperty: [Function],
    _dataProperties:
        [ 'id',
         'releases',
         'artist',
        'artistRels',
        'workRels',
        'title',
        'length',
        'artist',
        'producer',
        'vocal' ],
    data: [Function],
    setDataFields: [Function],
    isComplete: [Function],
    _loaded: true,
    _linkedEntities: [ 'releases', 'artists', 'artist-rels', 'work-rels' ],
    _loadedLinkedEntities: [],
    _readDataFunctions:
     [ releases: [Function],
       artists: [Function],
       'artist-credits': [Function],
   'artist-rels': [Function],
       'work-rels': [Function] ],
    id: '171305ad-1245-474f-8ac0-9bad28e8fdf0',
    load: [Function],
    update: [Function],
    loaded: [Function],
    readData: [Function],
    releases: [],
    loadReleaseList: [Function],
    artistCredits: [],
    loadArtistCredits: [Function],
    artistCreditsString: [Function],
    artistCreditsSortString: [Function],
    artistRels: [],
    loadArtistRels: [Function],
    getArtistRelsByType: [Function],
    workRels: [],
    loadWorkRels: [Function],
    getWorkRelByType: [Function],
    title: 'Ya Mama (U.K. Edition) (J-Swift remix)',
    length: '241000',
    artist: null,
    producer: null,
    vocal: null,
    _lookup: [Function] }